### ISSUE TITLE
지원(Applying) 기능 구현

### ISSUE THREAD

**Issue by LEEJaeHyeok97** [RecruitUs/Wanted-Server#21]
## 📝Description
> 유저(구직자)가 특정 채용 공고에 대해 지원서를 작성합니다.

## ☑️Todo
- [x] 채용 관련 도메인 생성
- [x] 코드 구현(service, dto, entity, repository, controller)
- [x] 유저 테이블과 회사 테이블 관계 연결

## 💬 ETC
- 지원서를 s3로 url로 받는 기능을 추가할 예정
