### ISSUE TITLE
[Todo] 향후 추가 & 개선 항목들

### ISSUE THREAD

**Issue by DryRains** [RecruitUs/Wanted-Server#38]
## 📝Description
> 아래는 해커톤 마감기한에 임박해 미처 완성되지 못하여 향후에 추가하거나 개선해야할 항목들입니다.
Priority : P1(Highest) ~ P3(Lowest)

## ☑️Todo
- [ ] 회원가입시 중복 이메일로 회원가입 방지 (P1)
- [ ] 유저 -> 기업 유저 / 구직자 유저 세분화 (단일 테이블 전략 사용하는 방향으로 고려중) (P1)
- [ ] 구직자 유저의 특정 기업 팔로우 (P3)
- [ ] 채용공고 지원시 지원자의 경력이 채용공고의 요구경력을 충족하지 못할경우 지원 방지 (P2)
- [ ] 채용공고 필터링 검색에 사용될 다양한 필터들 추가 (근무지(도시), 기술스택, 기업 태그 등) (P2)
- [ ] 채용공고 필터링 검색에 QueryDSL 이용해 동적쿼리로 구현 (P3)
- [ ] 채용공고 필터 선택한 상태에서 텍스트 검색 - 선택한 필터들을 가지고 있으면서 검색 텍스트도 포함하는 데이터 조회 (P3)
- [ ] 예외처리 세분 & 명확화 (P1)

## 💬 ETC
- 해결되었으면 체크해주시고, 추가적인 미완성 & 구현해야할 항목들이 있으면 위에 Todo 항목에 작성해주시길 바랍니다.

**Comment by LEEJaeHyeok97** [comment]
넵
